### ISSUE TITLE
Failed update readthedocs website automatically from scava-docs

### ISSUE THREAD

**Issue by ambpro** [eclipse-researchlabs/scava-docs#8]
Hello @borisbaldassari,

As we've discussed a couple of days ago, the readthedocs website at https://scava-docs.readthedocs.io still no be able to trigger the github webhooks workflow automatically in order to get the last update from the `scava-docs` repository build. The problem has been occured after the migration process into the new `eclipse-researchlabs` organization.

Could you please have a look on that ?
Thanks

**Comment by davidediruscio** [comment]
Fixed by @borisbaldassari and @phkrief . Thanks!
